import { GmPanelDef } from '../models/gm-panel.model';

/** Currency, shopping prices, and the d12 improvisation tables. */
export const TABLES_PANELS: readonly GmPanelDef[] = [
  {
    id: 'gold',
    title: 'Gold & Average Costs',
    colSpan: 1,
    defaultOrder: 230,
    keywords: ['coins', 'handful', 'bag', 'chest', 'currency', 'price', 'shopping', 'inn', 'mount'],
    body: {
      kind: 'static',
      blocks: [
        {
          kind: 'keyValue',
          entries: [
            { key: '1 Handful', value: '10 coins' },
            { key: '1 Bag', value: '10 Handfuls' },
            { key: '1 Chest', value: '10 Bags' },
          ],
        },
        {
          kind: 'table',
          headers: ['Purchase', 'Gold'],
          dense: true,
          rows: [
            ['Meals per night', '1 Handful'],
            ['Standard inn room per night', '1 Handful'],
            ['Luxury inn room per night', '1 Bag'],
            ['Carriage ride', '2 Handfuls'],
            ['Mount (horse, mule, etc.)', '3 Bags'],
            ['Specialized tools', '3 Handfuls'],
            ['Fine clothing', '3 Handfuls'],
            ['Luxury clothing', '1 Bag'],
            ['Tier 1 equipment (weapons, armor)', '1–5 Handfuls'],
            ['Tier 2 equipment (weapons, armor)', '1–2 Bags'],
            ['Tier 3 equipment (weapons, armor)', '5–10 Bags'],
            ['Tier 4 equipment (weapons, armor)', '1–2 Chests'],
          ],
        },
      ],
    },
  },
  {
    id: 'random-tables',
    title: 'Random Tables (d12)',
    colSpan: 2,
    defaultOrder: 240,
    keywords: ['improvise', 'generator', 'npc', 'name', 'description', 'location', 'item', 'roll'],
    body: {
      kind: 'static',
      blocks: [
        { kind: 'text', paragraphs: ['Locations & items — roll d12 for each column you need.'] },
        {
          kind: 'table',
          headers: ['d12', 'Feel', 'Material', 'Flavor', 'Function'],
          dense: true,
          rows: [
            ['1', 'Calm', 'Stone', 'Humming', 'Sealing'],
            ['2', 'Quiet', 'Crystal', 'Fractured', 'Binding'],
            ['3', 'Gloomy', 'Bone', 'Iridescent', 'Warding'],
            ['4', 'Bleak', 'Flesh', 'Glacial', 'Rending'],
            ['5', 'Tense', 'Scale', 'Cursed', 'Cursing'],
            ['6', 'Serene', 'Wood', 'Volcanic', 'Veiling'],
            ['7', 'Uneasy', 'Steel', 'Runed', 'Sapping'],
            ['8', 'Hushed', 'Chitin', 'Petrified', 'Piercing'],
            ['9', 'Ghostly', 'Cloth', 'Warped', 'Searing'],
            ['10', 'Sinister', 'Ceramic', 'Eldritch', 'Feasting'],
            ['11', 'Lonely', 'Glass', 'Luminous', 'Thirsting'],
            ['12', 'Radiant', 'Gem', 'Oozing', 'Haunting'],
          ],
        },
        { kind: 'text', paragraphs: ['Characters'] },
        {
          kind: 'table',
          headers: ['d12', 'Body', 'Attitude', 'Odor', 'Feature'],
          dense: true,
          rows: [
            ['1', 'Stocky', 'Snobby', 'Metal', 'Scar'],
            ['2', 'Lanky', 'Important', 'Sulfur', 'Limp'],
            ['3', 'Fat', 'Optimistic', 'Ash', 'Stutter'],
            ['4', 'Lean', 'Friendly', 'Mint', 'Stains'],
            ['5', 'Burly', 'Wise', 'Blood', 'Accent'],
            ['6', 'Chubby', 'Suave', 'Sweat', 'Birthmark'],
            ['7', 'Curvy', 'Greedy', 'Sour', 'Large nose'],
            ['8', 'Slender', 'Lazy', 'Wet fur', 'Piercing eyes'],
            ['9', 'Bony', 'Skeptical', 'Rotten', 'Blind'],
            ['10', 'Ripped', 'Eccentric', 'Citrus', 'Pet'],
            ['11', 'Plump', 'Moronic', 'Bread', 'Sweats'],
            ['12', 'Scrawny', 'Paranoid', 'Earth', 'Missing limb'],
          ],
        },
        { kind: 'text', paragraphs: ['Names — combine a first part with a second part.'] },
        {
          kind: 'table',
          headers: ['d12', 'Part 1', 'Part 2', 'Part 1 (alt)', 'Part 2 (alt)'],
          dense: true,
          rows: [
            ['1', 'Ka-', 'al', 'Sal-', 'lyssia'],
            ['2', 'Ju-', 'res', 'Fen-', 'shara'],
            ['3', 'El-', 'wen', 'Qui-', 'rella'],
            ['4', 'Yo-', 'rek', 'Ga-', 'wyn'],
            ['5', 'Bal-', 'dor', 'Bri-', 'ielle'],
            ['6', 'Za-', 'zok', 'Ny-', 'lyn'],
            ['7', 'Scha-', 'lara', 'Luth-', 'mira'],
            ['8', 'The-', 'lyn', 'Pyr-', 'indra'],
            ['9', 'Ar-', 'a', 'Quen-', 'sandra'],
            ['10', 'Va-', 'eira', 'Hala-', 'lani'],
            ['11', 'Ula-', 'ina', 'Vex-', 'ilah'],
            ['12', 'Ti-', 'alia', 'Jyr-', 'veth'],
          ],
        },
      ],
    },
  },
];
