import { CharacterSheetData } from '../models/character-sheet.model';
import { CreateCharacterSheetRequest } from '../models/character-sheet-api.model';

export function toCreateCharacterSheetRequest(data: CharacterSheetData): CreateCharacterSheetRequest {
  return {
    name: data.name,
    pronouns: data.pronouns,
    level: data.level,
    evasion: data.evasion,
    armorMax: data.armorMax,
    armorMarked: data.armorMarked,
    majorDamageThreshold: data.majorDamageThreshold,
    severeDamageThreshold: data.severeDamageThreshold,
    agilityModifier: data.agilityModifier,
    agilityMarked: data.agilityMarked,
    strengthModifier: data.strengthModifier,
    strengthMarked: data.strengthMarked,
    finesseModifier: data.finesseModifier,
    finesseMarked: data.finesseMarked,
    instinctModifier: data.instinctModifier,
    instinctMarked: data.instinctMarked,
    presenceModifier: data.presenceModifier,
    presenceMarked: data.presenceMarked,
    knowledgeModifier: data.knowledgeModifier,
    knowledgeMarked: data.knowledgeMarked,
    hitPointMax: data.hitPointMax,
    hitPointMarked: data.hitPointMarked,
    stressMax: data.stressMax,
    stressMarked: data.stressMarked,
    hopeMax: data.hopeMax,
    hopeMarked: data.hopeMarked,
    gold: data.gold,
    communityCardIds: data.communityCardIds,
    ancestryCardIds: data.ancestryCardIds,
    subclassCardIds: data.subclassCardIds,
    domainCardIds: data.domainCardIds,
    equippedDomainCardIds: data.equippedDomainCardIds,
    vaultDomainCardIds: data.vaultDomainCardIds,
    inventoryWeapons: data.inventoryWeapons,
    inventoryArmors: data.inventoryArmors,
    inventoryItems: [],
  };
}
